[[main]]
  name = "Home"
  url = ""
  weight = -110

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Cloud Native"
  identifier = "Links01"
  weight = -109
[[main]]
  parent = "Links01"
  name = "docker"
  url = "post/cn/docker/"
[[main]]
  parent = "Links01"
  name = "kubernetes"
  url = "post/cn/kubernetes/"

[[main]]
  name = "PL"
  identifier = "Links00"
  weight = -108
[[main]]
  parent = "Links00"
  name = "python"
  url = "post/pl/python/"
[[main]]
  parent = "Links00"
  name = "golang"
  url = "post/pl/golang/"
[[main]]
  parent = "Links00"
  name = "rust"
  url = "post/pl/rust/"

[[main]]
  name = "Linux"
  identifier = "Links02"
  weight = -107
[[main]]
  parent = "Links02"
  name = "shell"
  url = "post/linux/shell/"

[[main]]
  name = "Others"
  url = "post/others/"
  weight = -106

[[main]]
  name = "About"
  url = "about/"
  weight = -105

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/tpinellia"
# [[social]]
#   name = "twitter"
#   weight = 2
#   url = "https://twitter.com/#"
# [[social]]
#   name = "linkedin"
#   weight = 3
#   url = "https://www.linkedin.com/in/#"
# [[social]]
#   name = "rss"
#   weight = 4
#   url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"